common:
    seed: &seed 2020
    target: target
    metrics:
        name: f1_score
        params: {}
    drop:
        - miss_idx
    kaggle:
        data: False
        notebook: False

model:
    name: efficientnet_b3
    n_channels: &channel 3
    n_classes: 264
    pretrained: True
    multi_gpu: True
    avgpool:
        name: GeM
        params: {}
    head:
        act:
            name: ReLU
            params: {}
        drop:
            name: Dropout
            params:
                p: 0.5
        linear:
            name: Linear
            params:
                in_features: 1536
                out_features: 512
        act:
            name: ReLU
            params: {}
        drop:
            name: Dropout
            params:
                p: 0.5
        linear:
            name: Linear
            params:
                in_features: 512
                out_features: 264
    metric:

validation:
    name: StratifiedKFold
    params:
        n_splits: 5
        shuffle: True
        random_state: *seed
    split:
        y: ebird_code
        groups:
    weight:
        - 0.2
    single: True

data:
    train:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: &wsize 224
            height: &hsize 547
        n_channels: *channel
        epochs: 10
        loader:
            shuffle: True
            batch_size: 64
            num_workers: 4
        transforms:
        mixup: False
    valid:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 32
            num_workers: 4
        transforms:
        tta:
            iter_num: 1
    test:
        dataset_type: CustomDataset
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 1
            num_workers: 4
        transforms:
        tta:
            iter_num: 1

loss: 
    name: BCEWithLogitsLoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.001

scheduler:
    name: CosineAnnealingLR
    params:
        T_max: 10