common:
    seed: &seed 2020
    target: target
    metrics:
        name: f1_score
        params: {}
    drop:
        - miss_idx
    kaggle:
        data: True
        notebook: True

model:
    name: se_resnext50_32x4d
    n_channels: &channel 3
    n_classes: 264
    epochs: &epochs 30
    pretrained: True
    multi_gpu: True
    avgpool:
        name: GeM
        params: {}
    head:
        act:
            name: ReLU
            params: {}
        drop:
            name: Dropout
            params:
                p: 0.3
        linear:
            name: Linear
            params:
                in_features: 2048
                out_features: 264
    metric:

validation:
    name: StratifiedKFold
    params:
        n_splits: 5
        shuffle: True
        random_state: *seed
    split:
        y: ebird_code
        groups:
    weight:
        - 0.2
    single: True

data:
    train:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: &wsize 224
            height: &hsize 547
        n_channels: *channel
        loader:
            shuffle: True
            batch_size: 32
            num_workers: 4
        transforms:
        noise: 
            sample:
                - 0.50
                - 0.75
            water:
                - 0.75
                - 1.01
        shift: True
        mixup: True
    valid:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 32
            num_workers: 4
        transforms:
        noise:
        shift: False
        tta:
            iter_num: 1
    test:
        dataset_type: CustomDataset
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 1
            num_workers: 4
        transforms:
        noise:
        shift: False
        tta:
            iter_num: 1

loss: 
    name: BCEWithLogitsLoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.001

scheduler:
    name: CosineAnnealingLR
    params:
        T_max: *epochs